---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-console-ui
  namespace: stage
  labels:
    owner: hansamann
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql-console-ui
  template:
    metadata:
      labels:
        app: graphql-console-ui
      annotations:
        "sidecar.istio.io/inject": "true"
    spec:
      containers:
      - name: graphql-console-ui
        image: docker.io/hansamann/graphql-console-ui:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /usr/share/nginx/html/config.js
          subPath: config.js
      volumes:
      - name: config
        configMap:
          name: graphql-ui-config


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: graphql-ui-config
  namespace: stage
data:
  config.js: |
    window.backendConfig = {
      url: 'https://graphql-api.giga.cluster.extend.cx.cloud.sap'
    };

---
apiVersion: v1
kind: Service
metadata:
  name: graphql-console-ui
  namespace: stage
  labels:
    owner: hansamann
spec:
  selector:
    app: graphql-console-ui
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: gateway.kyma-project.io/v1alpha2
kind: Api
metadata:
  name: graphql-console-ui
  namespace: stage
  labels:
    owner: hansamann
spec:
  hostname: graphql-console-ui.giga.cluster.extend.cx.cloud.sap
  service:
    name: graphql-console-ui
    port: 80