---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: graphql-api
  namespace: stage
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: graphql-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyma-admin
subjects:
- kind: ServiceAccount
  name: graphql-api
  namespace: stage  